#!/bin/bash
# AWS WorkSpaces client entrypoint wrapper
# WebKitGTK rendering fixes for proot & software GL
export WEBKIT_DISABLE_COMPOSITING_MODE="${WEBKIT_DISABLE_COMPOSITING_MODE:-1}"
export WEBKIT_DISABLE_DMABUF_RENDERER="${WEBKIT_DISABLE_DMABUF_RENDERER:-1}"
export NO_AT_BRIDGE=1

# Start AWS WorkSpaces Client
exec workspacesclient "$@"
