#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/com.amazon.workspacesclient.svg
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/com.amazon.workspacesclient.png
rm -f $HOME/.local/share/icons/hicolor/256x256/apps/com.amazon.workspacesclient.png
rm -f $HOME/.local/share/icons/hicolor/48x48/apps/com.amazon.workspacesclient.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/aws-workspaces-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/aws-workspaces-pa.desktop
