#!/bin/bash
# Zap PA entrypoint wrapper
export WGPU_BACKEND="${WGPU_BACKEND:-auto}"
export MESA_GL_VERSION_OVERRIDE="${MESA_GL_VERSION_OVERRIDE:-3.3}"
export NO_AT_BRIDGE=1

cd /opt/zap || exit 1

if [ "$#" -gt 0 ]; then
  exec ./zap-oss "$@"
else
  exec ./zap-oss
fi
