#!/bin/bash
echo "Removing icon"
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/zap-pa.svg
rm -f $HOME/.local/share/icons/hicolor/scalable/apps/zap-pa.png
rm -f $HOME/.local/share/icons/hicolor/256x256/apps/zap-pa.png
rm -f $HOME/.local/share/icons/hicolor/48x48/apps/zap-pa.png
echo "Removing start menu entry"
rm -f $HOME/.local/share/applications/zap-pa.desktop
echo "Removing desktop shortcut"
rm -f $HOME/Desktop/zap-pa.desktop