name: Release on Tag
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish Release
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v7
    - uses: docker/setup-qemu-action@v4
    - uses: docker/setup-buildx-action@v4
    - run: bash ci-scripts/create-releases.sh
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v3
      with:
        tag_name: ${{ github.ref }}
        name: Release ${{ github.ref }}
        body_path: release-notes/current
        draft: false
        prerelease: false
        files: proot-apps-*
        token: ${{ secrets.GITHUB_TOKEN }}
